"""Streamlit review UI for fixing low-confidence OCR rows."""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import streamlit as st
from PIL import Image


def load_data(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    if "confidence" not in df.columns:
        df["confidence"] = 0.0
    df["confidence"] = pd.to_numeric(df["confidence"], errors="coerce").fillna(0.0)
    return df.sort_values("confidence").reset_index(drop=True)


def run(csv_path: Path, frames_dir: Path) -> None:
    st.set_page_config(page_title="Temperature OCR Review", layout="wide")
    st.title("Temperature OCR Review")
    st.caption("Review frames from lowest confidence upwards and correct any misreads.")

    df = load_data(csv_path)
    if df.empty:
        st.info("CSV is empty – nothing to review.")
        return

    threshold = st.slider("Highlight rows with confidence ≤", min_value=0.0, max_value=1.0, value=0.6, step=0.05)

    edits = {}
    for idx, row in df.iterrows():
        st.divider()
        cols = st.columns([2, 3])
        img_path = frames_dir / str(row.get("frame_file", ""))
        with cols[0]:
            if img_path.exists():
                st.image(Image.open(img_path), caption=f"{row['video_time']} | conf {row['confidence']:.2f}")
            else:
                st.warning(f"Missing frame: {img_path}")
        with cols[1]:
            st.write(f"**Time:** {row['video_time']}")
            st.write(f"**Confidence:** {row['confidence']:.2f}")
            if row["confidence"] <= threshold:
                st.warning("Below threshold – double check this value.")
            edits[idx] = st.text_input("Detected number", value=str(row.get("detected_number", "")), key=f"val_{idx}")

    if st.button("Save final_results.csv"):
        for idx, value in edits.items():
            df.loc[idx, "detected_number"] = value
        out_path = csv_path.with_name("final_results.csv")
        df.to_csv(out_path, index=False)
        st.success(f"Saved {out_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Launch the Streamlit review UI")
    parser.add_argument("--csv", required=True, help="results.csv generated by process_video.py")
    parser.add_argument("--frames_dir", default="./frames", help="Directory containing exported frames")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    run(Path(args.csv), Path(args.frames_dir))
